<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601193738 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Audit table for the AI categorization pass (ai_category_decision).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ai_category_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mode VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, previous_slugs JSON NOT NULL, proposed_slugs JSON NOT NULL, reason TEXT DEFAULT NULL, model VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_aicat_status ON ai_category_decision (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_aicat_event ON ai_category_decision (event_id)');
        $this->addSql('ALTER TABLE ai_category_decision ADD CONSTRAINT FK_681114A971F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ai_category_decision DROP CONSTRAINT FK_681114A971F7E88B');
        $this->addSql('DROP TABLE ai_category_decision');
    }
}
