<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601082916 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'AI-Dedup: ai_dedup_decision (Audit) + ai_dedup_day (Tages-Fingerprint).';
    }

    public function up(Schema $schema): void
    {
        // NOTE: daily_stat/page_stat/visitor_day are DBAL-only tables (not ORM
        // entities) — a schema_filter keeps the diff from touching them.
        $this->addSql('CREATE TABLE ai_dedup_day (day VARCHAR(10) NOT NULL, fingerprint VARCHAR(40) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (day))');
        $this->addSql('CREATE TABLE ai_dedup_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day DATE NOT NULL, reason TEXT DEFAULT NULL, model VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duplicate_event_id INT DEFAULT NULL, canonical_event_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B2763A121811C64 ON ai_dedup_decision (duplicate_event_id)');
        $this->addSql('CREATE INDEX IDX_9B2763A1E3331BC4 ON ai_dedup_decision (canonical_event_id)');
        $this->addSql('ALTER TABLE ai_dedup_decision ADD CONSTRAINT FK_9B2763A121811C64 FOREIGN KEY (duplicate_event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ai_dedup_decision ADD CONSTRAINT FK_9B2763A1E3331BC4 FOREIGN KEY (canonical_event_id) REFERENCES event (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ai_dedup_decision DROP CONSTRAINT FK_9B2763A121811C64');
        $this->addSql('ALTER TABLE ai_dedup_decision DROP CONSTRAINT FK_9B2763A1E3331BC4');
        $this->addSql('DROP TABLE ai_dedup_day');
        $this->addSql('DROP TABLE ai_dedup_decision');
    }
}
