<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260529175352 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE import_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration_ms INT NOT NULL, status VARCHAR(10) NOT NULL, seen INT NOT NULL, created INT NOT NULL, updated INT NOT NULL, unchanged INT NOT NULL, duplicates INT NOT NULL, errors INT NOT NULL, dry_run BOOLEAN NOT NULL, message TEXT DEFAULT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_import_run_started ON import_run (started_at)');
        $this->addSql('CREATE INDEX idx_import_run_source ON import_run (source_id)');
        $this->addSql('ALTER TABLE import_run ADD CONSTRAINT FK_C41B0440953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE import_run DROP CONSTRAINT FK_C41B0440953C1C61');
        $this->addSql('DROP TABLE import_run');
    }
}
