<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260529152242 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, color VARCHAR(7) NOT NULL, icon VARCHAR(16) DEFAULT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(300) NOT NULL, slug VARCHAR(320) NOT NULL, description TEXT DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, all_day BOOLEAN NOT NULL, location_text VARCHAR(255) DEFAULT NULL, source_url VARCHAR(1024) DEFAULT NULL, image_url VARCHAR(1024) DEFAULT NULL, price VARCHAR(120) DEFAULT NULL, organizer VARCHAR(200) DEFAULT NULL, external_id VARCHAR(191) DEFAULT NULL, content_hash VARCHAR(40) NOT NULL, dedup_key VARCHAR(191) NOT NULL, status VARCHAR(20) NOT NULL, raw JSON NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, venue_id INT DEFAULT NULL, category_id INT DEFAULT NULL, source_id INT NOT NULL, duplicate_of_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA740A73EBA ON event (venue_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA712469DE2 ON event (category_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7953C1C61 ON event (source_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA72CC33300 ON event (duplicate_of_id)');
        $this->addSql('CREATE INDEX idx_event_starts_at ON event (starts_at)');
        $this->addSql('CREATE INDEX idx_event_dedup_key ON event (dedup_key)');
        $this->addSql('CREATE INDEX idx_event_status ON event (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_source_external ON event (source_id, external_id)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(64) NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(20) NOT NULL, url VARCHAR(1024) DEFAULT NULL, importer VARCHAR(64) DEFAULT NULL, enabled BOOLEAN NOT NULL, config JSON NOT NULL, last_run_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_status VARCHAR(1024) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F738A90ABA9 ON source (key)');
        $this->addSql('CREATE TABLE venue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, street VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, city VARCHAR(120) NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, dedup_key VARCHAR(200) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_venue_city ON venue (city)');
        $this->addSql('CREATE UNIQUE INDEX uniq_venue_dedup ON venue (dedup_key)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA740A73EBA FOREIGN KEY (venue_id) REFERENCES venue (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA712469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA72CC33300 FOREIGN KEY (duplicate_of_id) REFERENCES event (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA740A73EBA');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA712469DE2');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7953C1C61');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA72CC33300');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE venue');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
