<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260611180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Multi-region foundation: region table, region ownership for sources/events/venues, and per-region AI dedup fingerprints.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, region_key VARCHAR(64) NOT NULL, site_name VARCHAR(80) NOT NULL, area_name VARCHAR(120) NOT NULL, tagline VARCHAR(160) NOT NULL, canonical_host VARCHAR(120) NOT NULL, host_aliases JSON NOT NULL, theme_color VARCHAR(7) NOT NULL, logo_letter VARCHAR(1) NOT NULL, default_city VARCHAR(120) NOT NULL, cities JSON NOT NULL, city_aliases JSON NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_region_key ON region (region_key)');
        $this->addSql('CREATE UNIQUE INDEX uniq_region_host ON region (canonical_host)');

        $this->addRegionSql('guetersloh', 'dalketicker', 'Kreis Gütersloh', 'Was läuft im Kreis Gütersloh', 'dalketicker.de', ['www.dalketicker.de', 'dalketicker.neuhaus.nrw', 'dalketicker.traefik.me'], '#0a8da3', 'd', 'Kreis Gütersloh');
        $this->addRegionSql('paderborn', 'paderticker', 'Kreis Paderborn', 'Was läuft im Kreis Paderborn', 'paderticker.neuhaus.nrw', ['paderticker.de', 'www.paderticker.de', 'paderticker.traefik.me'], '#1d7f64', 'p', 'Kreis Paderborn');
        $this->addRegionSql('minden-luebbecke', 'weserticker', 'Kreis Minden-Lübbecke', 'Was läuft im Kreis Minden-Lübbecke', 'weserticker.neuhaus.nrw', ['weserticker.de', 'www.weserticker.de', 'weserticker.traefik.me'], '#2563eb', 'w', 'Kreis Minden-Lübbecke');
        $this->addRegionSql('bielefeld', 'sparrenticker', 'Bielefeld', 'Was läuft in Bielefeld', 'sparrenticker.de', ['www.sparrenticker.de', 'sparrenticker.traefik.me'], '#e30014', 's', 'Bielefeld');

        $this->addSql('DROP INDEX UNIQ_5F8A7F738A90ABA9');
        $this->addSql('ALTER TABLE source RENAME COLUMN key TO source_key');
        $this->addSql('ALTER TABLE source ADD region_id INT DEFAULT NULL');
        $this->addSql("UPDATE source SET region_id = (SELECT id FROM region WHERE region_key = 'guetersloh')");
        $this->addSql('ALTER TABLE source ALTER region_id SET NOT NULL');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_SOURCE_REGION FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5F8A7F7398260155 ON source (region_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_source_region_key ON source (region_id, source_key)');

        $this->addSql('ALTER TABLE event ADD region_id INT DEFAULT NULL');
        $this->addSql('UPDATE event e SET region_id = s.region_id FROM source s WHERE e.source_id = s.id');
        $this->addSql('ALTER TABLE event ALTER region_id SET NOT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_EVENT_REGION FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_3BAE0AA798260155 ON event (region_id)');
        $this->addSql('CREATE INDEX idx_event_region_starts_at ON event (region_id, starts_at)');

        $this->addSql('DROP INDEX uniq_venue_dedup');
        $this->addSql('ALTER TABLE venue ADD region_id INT DEFAULT NULL');
        $this->addSql("UPDATE venue SET region_id = (SELECT id FROM region WHERE region_key = 'guetersloh')");
        $this->addSql('ALTER TABLE venue ALTER region_id SET NOT NULL');
        $this->addSql('ALTER TABLE venue ADD CONSTRAINT FK_VENUE_REGION FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_91911B0D98260155 ON venue (region_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_venue_region_dedup ON venue (region_id, dedup_key)');

        $this->addSql("ALTER TABLE ai_dedup_day ADD region_key VARCHAR(64) DEFAULT 'guetersloh' NOT NULL");
        $this->addSql('ALTER TABLE ai_dedup_day ALTER region_key DROP DEFAULT');
        $this->addSql('ALTER TABLE ai_dedup_day DROP CONSTRAINT ai_dedup_day_pkey');
        $this->addSql('ALTER TABLE ai_dedup_day ADD PRIMARY KEY (region_key, day)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ai_dedup_day DROP CONSTRAINT ai_dedup_day_pkey');
        $this->addSql('ALTER TABLE ai_dedup_day DROP region_key');
        $this->addSql('ALTER TABLE ai_dedup_day ADD PRIMARY KEY (day)');

        $this->addSql('ALTER TABLE venue DROP CONSTRAINT FK_VENUE_REGION');
        $this->addSql('DROP INDEX uniq_venue_region_dedup');
        $this->addSql('DROP INDEX IDX_91911B0D98260155');
        $this->addSql('ALTER TABLE venue DROP region_id');
        $this->addSql('CREATE UNIQUE INDEX uniq_venue_dedup ON venue (dedup_key)');

        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_EVENT_REGION');
        $this->addSql('DROP INDEX idx_event_region_starts_at');
        $this->addSql('DROP INDEX IDX_3BAE0AA798260155');
        $this->addSql('ALTER TABLE event DROP region_id');

        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_SOURCE_REGION');
        $this->addSql('DROP INDEX uniq_source_region_key');
        $this->addSql('DROP INDEX IDX_5F8A7F7398260155');
        $this->addSql('ALTER TABLE source DROP region_id');
        $this->addSql('ALTER TABLE source RENAME COLUMN source_key TO key');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F738A90ABA9 ON source (key)');

        $this->addSql('DROP TABLE region');
    }

    /** @param list<string> $aliases */
    private function addRegionSql(string $key, string $siteName, string $areaName, string $tagline, string $host, array $aliases, string $color, string $letter, string $defaultCity): void
    {
        $this->addSql('INSERT INTO region (region_key, site_name, area_name, tagline, canonical_host, host_aliases, theme_color, logo_letter, default_city, cities, city_aliases, enabled) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [
            $key,
            $siteName,
            $areaName,
            $tagline,
            $host,
            json_encode($aliases, \JSON_THROW_ON_ERROR),
            $color,
            $letter,
            $defaultCity,
            '[]',
            '{}',
            true,
        ]);
    }
}
